name = "DRSOM"
uuid = "d175e27a-564a-485c-86b6-52e0284acaa2"
authors = ["C. Zhang <chuwzhang@gmail.com>", "Y. Ye <yyye@stanford.edu>"]
version = "0.3.0"

[deps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Distributions = "0.25.65"
ForwardDiff = "0.10.30"
KrylovKit = "0.5.4"
LineSearches = "7.1.1"
Parameters = "0.12.3"
ReverseDiff = "1.14.1"
julia = "^1.8.2"
